# Generated by Django 6.0.4 on 2026-04-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('etsy', 'Etsy'), ('popcustoms', 'PopCustoms')], max_length=32)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('etsy', 'Etsy'), ('popcustoms', 'PopCustoms')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('account_identifier', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('provider', 'account_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ExternalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('etsy', 'Etsy'), ('popcustoms', 'PopCustoms')], max_length=32)),
                ('external_listing_id', models.CharField(max_length=255)),
                ('external_product_id', models.CharField(blank=True, max_length=255)),
                ('external_variant_id', models.CharField(blank=True, max_length=255)),
                ('listing_url', models.URLField(blank=True)),
                ('sync_state', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('channel_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='connectors.channelaccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_listings', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_listings', to='catalog.productvariant')),
            ],
            options={
                'unique_together': {('provider', 'external_listing_id')},
            },
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('etsy', 'Etsy'), ('popcustoms', 'PopCustoms')], max_length=32)),
                ('external_order_id', models.CharField(max_length=255)),
                ('external_status', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('channel_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='connectors.channelaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_records', to='orders.order')),
            ],
            options={
                'unique_together': {('provider', 'external_order_id')},
            },
        ),
    ]
