# Generated by Codex on 2026-04-25

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_storesettings_productvariant_height_in_and_more'),
        ('orders', '0005_order_coupon_code_order_discount_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('promotion_type', models.CharField(choices=[('percent_off', 'Percent off'), ('fixed_off', 'Fixed off'), ('sale_price', 'Sale price override'), ('free_shipping', 'Free shipping')], max_length=24)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('combinable', models.BooleanField(default=False)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('popcustoms', 'PopCustoms')], default='manual', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['priority', 'name']},
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('carrier', models.CharField(choices=[('ups', 'UPS'), ('usps', 'USPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('estimated_min_days', models.PositiveIntegerField(default=3)),
                ('estimated_max_days', models.PositiveIntegerField(default=7)),
            ],
            options={'ordering': ['carrier', 'name']},
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('countries', models.TextField(default='US', help_text='Comma-separated ISO country codes. Use * for worldwide.')),
                ('regions', models.TextField(blank=True, help_text='Optional comma-separated state/region codes.')),
                ('unavailable_countries', models.TextField(blank=True, help_text='Comma-separated country codes blocked for this zone.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_total_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('first_order_only', models.BooleanField(default=False)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('combinable', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_created', to=settings.AUTH_USER_MODEL)),
                ('promotions', models.ManyToManyField(blank=True, related_name='coupons', to='pricing.promotion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='pricing.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('product', 'Single product'), ('products', 'Product list'), ('sku', 'Single SKU'), ('skus', 'SKU list'), ('page', 'Single page'), ('pages', 'Page list'), ('global', 'Global')], default='global', max_length=20)),
                ('skus', models.TextField(blank=True, help_text='Comma-separated SKU list.')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_scopes', to='catalog.storepage')),
                ('pages', models.ManyToManyField(blank=True, related_name='promotion_list_scopes', to='catalog.storepage')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_scopes', to='catalog.product')),
                ('products', models.ManyToManyField(blank=True, related_name='promotion_list_scopes', to='catalog.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='pricing.promotion')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_scopes', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('flat', 'Flat'), ('weight_tier', 'Weight tier'), ('price_tier', 'Price tier'), ('free_shipping', 'Free shipping override')], default='flat', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_weight_oz', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_weight_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('fallback', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=100)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='pricing.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='pricing.shippingzone')),
            ],
            options={'ordering': ['priority', 'amount']},
        ),
        migrations.CreateModel(
            name='ShippingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_webhook_events', to='orders.order')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'event_id'], name='pricing_shi_provide_c76de2_idx')],
            },
        ),
    ]
