# Generated by Django 6.0.4 on 2026-04-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_storepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_custom_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_request_help_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_request_label',
            field=models.CharField(blank=True, default='Custom request', max_length=120),
        ),
    ]
