# Generated by Django 6.0.4 on 2026-04-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_allow_custom_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Supported formats: MP4, WebM, Ogg (max 100MB)', upload_to='products/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/video_thumbnails/')),
                ('title', models.CharField(default='Product video', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='catalog.product')),
            ],
        ),
    ]
