# Generated by Django 6.0.4 on 2026-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productimage_image_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='max_order_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional per-order cap for fairness. Leave blank for no cap beyond stock.', null=True),
        ),
    ]
