# Generated by Django 6.0.4 on 2026-04-25 07:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_storepage_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TG11 Shop', max_length=120)),
                ('tagline', models.CharField(default='Products, checkout, and fulfillment in one place.', max_length=255)),
                ('motd', models.CharField(default='TG11 Shop control deck: products, checkout, and fulfillment in one place.', max_length=255)),
                ('support_email', models.EmailField(default='support@shop.tg11.org', max_length=254)),
                ('footer_text', models.CharField(default='Payments run through Stripe Checkout. Fulfillment jobs queue after payment.', max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='store/branding/')),
                ('favicon', models.ImageField(blank=True, upload_to='store/branding/')),
                ('social_image', models.ImageField(blank=True, upload_to='store/branding/')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('order_prefix', models.CharField(default='TG11', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height_in',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='hs_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length_in',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='origin_country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='supplier_compare_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='supplier_sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='supplier_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='supplier_sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_oz',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_in',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
