# Generated by Codex on 2026-04-25

from decimal import Decimal

from django.db import migrations


def create_default_store_settings(apps, schema_editor):
    StoreSettings = apps.get_model('catalog', 'StoreSettings')
    StoreSettings.objects.get_or_create(
        pk=1,
        defaults={
            'name': 'TG11 Shop',
            'tagline': 'Products, checkout, and fulfillment in one place.',
            'motd': 'TG11 Shop control deck: products, checkout, and fulfillment in one place.',
            'support_email': 'support@shop.tg11.org',
            'footer_text': 'Payments run through Stripe Checkout. Fulfillment jobs queue after payment.',
            'free_shipping_threshold': Decimal('100.00'),
            'currency': 'usd',
            'order_prefix': 'TG11',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_storesettings_productvariant_height_in_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_store_settings, migrations.RunPython.noop),
    ]
