# Generated by Django 6.0.4 on 2026-04-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_default_store_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='productvideo',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.product'),
        ),
    ]
