# Generated by Django 6.0.4 on 2026-04-25 22:55

from django.db import migrations
from django.db import models


SIZE_ORDER_MAP = {
    'xxs': 0,
    'extraextrasmall': 0,
    'xs': 1,
    'xsmall': 1,
    'extrasmall': 1,
    's': 2,
    'small': 2,
    'm': 3,
    'medium': 3,
    'l': 4,
    'large': 4,
    'xl': 5,
    'xlarge': 5,
    'extralarge': 5,
    'xxl': 6,
    '2xl': 6,
    '2xlarge': 6,
    'extraextralarge': 6,
    'xxxl': 7,
    '3xl': 7,
    '3xlarge': 7,
    '4xl': 8,
    '4xlarge': 8,
    '5xl': 9,
    '5xlarge': 9,
    '6xl': 10,
    '6xlarge': 10,
    '7xl': 11,
    '7xlarge': 11,
    '8xl': 12,
    '8xlarge': 12,
}


DISPLAY_LABELS = {
    'xxs': 'XXS',
    'xs': 'XS',
    'xsmall': 'XS',
    'extrasmall': 'XS',
    's': 'Small',
    'small': 'Small',
    'm': 'Medium',
    'medium': 'Medium',
    'l': 'Large',
    'large': 'Large',
    'xl': 'XL',
    'xlarge': 'XL',
    'extralarge': 'XL',
    '2xl': '2XL',
    '2xlarge': '2XL',
    'xxl': '2XL',
    '3xl': '3XL',
    '3xlarge': '3XL',
    'xxxl': '3XL',
    '4xl': '4XL',
    '4xlarge': '4XL',
    '5xl': '5XL',
    '5xlarge': '5XL',
    '6xl': '6XL',
    '6xlarge': '6XL',
    '7xl': '7XL',
    '7xlarge': '7XL',
    '8xl': '8XL',
    '8xlarge': '8XL',
}


def normalize(value):
    if not value:
        return ''
    return ''.join(character.lower() for character in value if character.isalnum())


def forward(apps, schema_editor):
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    for variant in ProductVariant.objects.only('pk', 'title', 'size_label', 'sort_order').iterator(chunk_size=200):
        key = normalize(variant.size_label or variant.title)
        label = DISPLAY_LABELS.get(key, '')
        sort_order = SIZE_ORDER_MAP.get(key)
        update_fields = []
        if label and not variant.size_label:
            variant.size_label = label
            update_fields.append('size_label')
        elif label and variant.size_label:
            canonical = DISPLAY_LABELS.get(normalize(variant.size_label), '')
            if canonical and canonical != variant.size_label:
                variant.size_label = canonical
                update_fields.append('size_label')
        if sort_order is not None and variant.sort_order == 0:
            variant.sort_order = sort_order
            update_fields.append('sort_order')
        if update_fields:
            variant.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_productvideo_options_productvideo_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product__name', 'sort_order', '-is_default', 'title']},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='body_length_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='chest_width_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_label',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sleeve_length_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]