# Generated by Django 6.0.4 on 2026-04-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0003_product_allow_custom_requests_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'variant', 'custom_request'), name='unique_cart_variant_custom_request'),
        ),
    ]
