# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon_code',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
