# Generated by Django 6.0.4 on 2026-04-23 18:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('queued', 'Queued'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='unsubmitted', max_length=20)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('etsy', 'Etsy'), ('popcustoms', 'PopCustoms')], default='internal', max_length=20)),
                ('external_order_id', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('connector_slug', models.CharField(blank=True, max_length=64)),
                ('sync_state', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('etsy', 'Etsy'), ('popcustoms', 'PopCustoms')], default='internal', max_length=20)),
                ('external_listing_id', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant')),
            ],
        ),
    ]
