# Generated by Django 6.0.4 on 2026-04-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_custom_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('queued', 'Queued'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='Carrier tracking number (e.g., UPS, FedEx, USPS)', max_length=255)),
                ('carrier', models.CharField(blank=True, choices=[('ups', 'UPS'), ('fedex', 'FedEx'), ('usps', 'USPS'), ('dhl', 'DHL'), ('other', 'Other')], max_length=50)),
                ('tracking_url', models.URLField(blank=True, help_text='Direct link to tracking information')),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the customer')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether notification email has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_updates_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_updates', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Fulfillment updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
